/**
 * Declarative specifications for reusable MCP marketing prompts. Each prompt is
 * rendered into a structured instruction that: derives business context, states
 * required and optional inputs, avoids unnecessary personal data, explains
 * assumptions, selects relevant skills, requests structured output, and flags
 * actions that require human approval.
 */
export interface PromptSpec {
  name: string;
  title: string;
  description: string;
  requiredInputs: string[];
  optionalInputs: string[];
  relevantSkills: string[];
  outputStructure: string[];
  approvalNotes: string;
}

export const PROMPT_SPECS: PromptSpec[] = [
  {
    name: 'audit_digital_marketing',
    title: 'Audit my digital marketing',
    description: 'Produce a structured audit of current digital marketing across channels.',
    requiredInputs: ['company/website', 'primary business objective', 'target market'],
    optionalInputs: ['current channels', 'analytics access', 'known problems', 'budget'],
    relevantSkills: ['foundation.digital-presence-audit', 'analytics.measurement-strategy', 'seo.seo-audit'],
    outputStructure: ['maturity summary', 'per-channel findings', 'risks', 'prioritised recommendations', 'next actions'],
    approvalNotes: 'Read-only analysis; no approval required.',
  },
  {
    name: 'create_marketing_strategy',
    title: 'Create a marketing strategy',
    description: 'Build a measurable marketing strategy linking objectives to channels and KPIs.',
    requiredInputs: ['business objective', 'audience', 'offer', 'budget range', 'time horizon'],
    optionalInputs: ['positioning', 'constraints', 'current performance'],
    relevantSkills: ['strategy.annual-marketing-strategy', 'strategy.channel-mix-planning', 'analytics.kpi-framework'],
    outputStructure: ['objectives', 'audience & positioning', 'channel mix', 'measurement plan', 'budget', 'roadmap', 'risks'],
    approvalNotes: 'Planning output; approval needed only before executing spend.',
  },
  {
    name: 'create_go_to_market',
    title: 'Create a go-to-market strategy',
    description: 'Design a GTM plan from research through launch and measurement.',
    requiredInputs: ['product/service', 'target segment', 'value proposition', 'launch timeframe'],
    optionalInputs: ['competitors', 'pricing', 'sales motion'],
    relevantSkills: ['strategy.go-to-market-strategy', 'positioning.positioning-statement', 'strategy.channel-mix-planning'],
    outputStructure: ['market & customer', 'positioning', 'offer & messaging', 'funnel', 'channels', 'measurement', 'budget', 'timeline', 'risks', 'approvals'],
    approvalNotes: 'Approval required before launching campaigns or spend.',
  },
  {
    name: 'define_icp',
    title: 'Define my ideal customer profile',
    description: 'Create an evidence-based ICP.',
    requiredInputs: ['product/service', 'best current customers or hypotheses', 'market'],
    optionalInputs: ['firmographics', 'win/loss data', 'CRM segments'],
    relevantSkills: ['customer-research.ideal-customer-profile', 'customer-research.firmographic-segmentation'],
    outputStructure: ['ICP definition', 'inclusion/exclusion criteria', 'evidence & assumptions', 'validation plan'],
    approvalNotes: 'Read-only; avoid collecting unnecessary personal data.',
  },
  {
    name: 'create_buyer_personas',
    title: 'Create buyer personas',
    description: 'Develop buyer personas grounded in jobs-to-be-done.',
    requiredInputs: ['ICP or target audience', 'product/service'],
    optionalInputs: ['interview notes', 'reviews', 'survey data'],
    relevantSkills: ['customer-research.buyer-persona-development', 'customer-research.jobs-to-be-done'],
    outputStructure: ['personas', 'goals & pains', 'objections', 'channels', 'messaging angles', 'assumptions'],
    approvalNotes: 'Read-only.',
  },
  {
    name: 'analyse_competitors',
    title: 'Analyse my competitors',
    description: 'Structured competitor analysis without fabricating proprietary data.',
    requiredInputs: ['your company', 'named competitors or category', 'market'],
    optionalInputs: ['positioning', 'known differentiators'],
    relevantSkills: ['market-research.competitor-positioning-analysis', 'market-research.swot-analysis'],
    outputStructure: ['competitor set', 'positioning map', 'strengths/weaknesses', 'opportunities', 'evidence grade'],
    approvalNotes: 'Read-only; do not fabricate proprietary competitor data.',
  },
  {
    name: 'create_full_funnel_campaign',
    title: 'Create a full-funnel campaign',
    description: 'Plan a coordinated campaign across awareness, consideration and decision.',
    requiredInputs: ['objective', 'audience', 'offer', 'budget', 'timeframe'],
    optionalInputs: ['channels', 'creative constraints', 'conversion definition'],
    relevantSkills: ['strategy.full-funnel-strategy', 'paid-social.social-campaign-architecture', 'content.content-strategy'],
    outputStructure: ['objective & KPIs', 'audiences by stage', 'channel plan', 'creative brief', 'tracking plan', 'budget', 'approvals'],
    approvalNotes: 'Approval required before launching ads or spend.',
  },
  {
    name: 'create_content_strategy',
    title: 'Create a content strategy',
    description: 'Build a content strategy with pillars, clusters and a distribution plan.',
    requiredInputs: ['audience', 'business objective', 'topics or product area'],
    optionalInputs: ['existing content', 'keyword data', 'brand voice'],
    relevantSkills: ['content.content-strategy', 'content.content-pillar-development', 'seo.topic-cluster-planning'],
    outputStructure: ['pillars', 'clusters', 'formats', 'calendar outline', 'distribution', 'measurement'],
    approvalNotes: 'Planning; publishing requires approval.',
  },
  {
    name: 'create_content_calendar',
    title: 'Create a 90-day content calendar',
    description: 'Produce a 90-day editorial calendar aligned to objectives and channels.',
    requiredInputs: ['audience', 'objective', 'channels', 'cadence'],
    optionalInputs: ['pillars', 'seasonal events', 'resources'],
    relevantSkills: ['content.editorial-calendar', 'content.content-distribution-plan'],
    outputStructure: ['weekly plan', 'formats & channels', 'owners', 'KPIs'],
    approvalNotes: 'Publishing requires approval.',
  },
  {
    name: 'seo_audit',
    title: 'Perform an SEO audit',
    description: 'Run a structured SEO audit across technical, on-page and off-page.',
    requiredInputs: ['website', 'target market/locale'],
    optionalInputs: ['Search Console/analytics data', 'priority pages', 'competitors'],
    relevantSkills: ['seo.seo-audit', 'seo.technical-seo-audit', 'seo.on-page-seo-audit'],
    outputStructure: ['findings by area', 'severity', 'prioritised fixes', 'expected impact (qualified)', 'next actions'],
    approvalNotes: 'Read-only; do not promise rankings or traffic.',
  },
  {
    name: 'seo_content_cluster',
    title: 'Create an SEO content cluster',
    description: 'Plan a pillar-and-cluster content structure for a topic.',
    requiredInputs: ['topic', 'audience', 'target market/locale'],
    optionalInputs: ['seed keywords', 'existing pages'],
    relevantSkills: ['seo.keyword-clustering', 'seo.topic-cluster-planning', 'seo.content-brief-creation'],
    outputStructure: ['pillar page', 'cluster topics', 'intent mapping', 'internal-linking plan', 'briefs'],
    approvalNotes: 'Planning; publishing requires approval.',
  },
  {
    name: 'plan_google_ads',
    title: 'Plan a Google Ads campaign',
    description: 'Design a Google Ads campaign architecture and plan.',
    requiredInputs: ['objective', 'budget', 'target market', 'conversion definition'],
    optionalInputs: ['keywords', 'landing pages', 'existing account data'],
    relevantSkills: ['paid-search.campaign-architecture', 'paid-search.keyword-planning', 'paid-search.search-ad-copy'],
    outputStructure: ['campaign structure', 'keywords & match types', 'negatives', 'ad copy', 'bidding', 'tracking', 'budget', 'approvals'],
    approvalNotes: 'Approval required before launch or budget changes.',
  },
  {
    name: 'plan_meta_ads',
    title: 'Plan a Meta Ads campaign',
    description: 'Design a Meta (Facebook/Instagram) Ads campaign plan.',
    requiredInputs: ['objective', 'budget', 'audience', 'offer'],
    optionalInputs: ['creative assets', 'pixel/CAPI status', 'catalogue'],
    relevantSkills: ['paid-social.social-campaign-architecture', 'paid-social.audience-planning', 'paid-social.creative-brief-development'],
    outputStructure: ['campaign structure', 'audiences', 'creative concepts', 'budget', 'tracking', 'approvals'],
    approvalNotes: 'Approval required before launch or budget changes.',
  },
  {
    name: 'social_calendar',
    title: 'Create a social-media calendar',
    description: 'Plan an organic social calendar by platform.',
    requiredInputs: ['audience', 'objective', 'platforms', 'cadence'],
    optionalInputs: ['content pillars', 'brand voice'],
    relevantSkills: ['organic-social.social-content-calendar', 'organic-social.social-content-pillars'],
    outputStructure: ['calendar by platform', 'formats', 'hooks', 'KPIs'],
    approvalNotes: 'Publishing requires approval.',
  },
  {
    name: 'email_nurture_sequence',
    title: 'Create an email nurture sequence',
    description: 'Design a lead-nurture email sequence.',
    requiredInputs: ['audience/segment', 'objective', 'offer'],
    optionalInputs: ['ESP', 'existing content', 'consent status'],
    relevantSkills: ['email.lead-nurture-series', 'email.email-body-creation'],
    outputStructure: ['sequence map', 'per-email brief', 'personalisation', 'measurement', 'compliance checks'],
    approvalNotes: 'Sending requires consent, suppression checks and approval.',
  },
  {
    name: 'lifecycle_campaign',
    title: 'Design a lifecycle campaign',
    description: 'Design a lifecycle/CRM campaign across stages.',
    requiredInputs: ['lifecycle stage focus', 'objective', 'segments'],
    optionalInputs: ['CRM data', 'triggers'],
    relevantSkills: ['crm.lifecycle-stage-design', 'crm.workflow-design'],
    outputStructure: ['stage triggers', 'messaging', 'channels', 'measurement', 'compliance'],
    approvalNotes: 'Contacting customers requires approval and consent checks.',
  },
  {
    name: 'audit_landing_page',
    title: 'Audit a landing page',
    description: 'Run a CRO audit of a landing page.',
    requiredInputs: ['landing page URL or content', 'objective/conversion action', 'audience'],
    optionalInputs: ['analytics/heatmaps', 'traffic source'],
    relevantSkills: ['cro.landing-page-audit', 'cro.value-proposition-clarity-review'],
    outputStructure: ['findings', 'friction points', 'hypotheses', 'prioritised tests'],
    approvalNotes: 'Read-only analysis.',
  },
  {
    name: 'create_ab_test',
    title: 'Create an A/B test',
    description: 'Design a rigorous A/B test with sample-size guidance.',
    requiredInputs: ['metric', 'baseline rate', 'minimum detectable effect'],
    optionalInputs: ['traffic volume', 'guardrail metrics'],
    relevantSkills: ['experimentation.ab-test-design', 'experimentation.sample-size-estimation'],
    outputStructure: ['hypothesis', 'variants', 'sample size', 'duration', 'guardrails', 'analysis plan'],
    approvalNotes: 'Planning; live changes require approval.',
  },
  {
    name: 'build_tracking_plan',
    title: 'Build a tracking plan',
    description: 'Design an event taxonomy and tracking plan.',
    requiredInputs: ['conversion definitions', 'key user actions', 'platforms'],
    optionalInputs: ['current tags', 'consent mode status'],
    relevantSkills: ['analytics.tracking-plan-design', 'analytics.event-taxonomy', 'analytics.utm-governance'],
    outputStructure: ['events', 'parameters', 'naming conventions', 'UTM rules', 'validation steps'],
    approvalNotes: 'Read-only; production tag changes require approval.',
  },
  {
    name: 'analyse_campaign_performance',
    title: 'Analyse campaign performance',
    description: 'Diagnose campaign performance against objectives.',
    requiredInputs: ['campaign objective/KPIs', 'metrics or data access', 'date range'],
    optionalInputs: ['targets', 'comparison period'],
    relevantSkills: ['reporting.campaign-performance-report', 'analytics.marketing-performance-diagnosis'],
    outputStructure: ['KPI vs target', 'drivers', 'anomalies', 'recommendations', 'owners'],
    approvalNotes: 'Read-only.',
  },
  {
    name: 'monthly_marketing_report',
    title: 'Create a monthly marketing report',
    description: 'Produce a monthly marketing report with insights and actions.',
    requiredInputs: ['date range', 'KPIs', 'data access or figures'],
    optionalInputs: ['targets', 'prior period', 'segments'],
    relevantSkills: ['reporting.monthly-marketing-report', 'reporting.executive-summary'],
    outputStructure: ['executive summary', 'channel sections', 'anomalies', 'recommendations', 'assumptions'],
    approvalNotes: 'Read-only.',
  },
  {
    name: 'diagnose_declining_conversions',
    title: 'Diagnose declining conversions',
    description: 'Root-cause a decline in conversions.',
    requiredInputs: ['conversion definition', 'affected period', 'funnel data or access'],
    optionalInputs: ['recent changes', 'segments', 'tracking status'],
    relevantSkills: ['reporting.root-cause-analysis', 'cro.funnel-drop-off-analysis'],
    outputStructure: ['hypotheses ranked', 'evidence', 'checks to run', 'recommended fixes'],
    approvalNotes: 'Read-only.',
  },
  {
    name: 'allocate_budget',
    title: 'Allocate a marketing budget',
    description: 'Allocate budget across channels with assumptions and ranges.',
    requiredInputs: ['total budget', 'objectives', 'time period'],
    optionalInputs: ['historical performance', 'constraints', 'targets'],
    relevantSkills: ['budgeting.channel-budget-allocation', 'budgeting.scenario-planning'],
    outputStructure: ['allocation by channel', 'assumptions', 'scenarios', 'pacing', 'review cadence'],
    approvalNotes: 'Spend execution requires approval.',
  },
  {
    name: 'saas_growth_plan',
    title: 'Create a SaaS growth plan',
    description: 'Build a SaaS growth plan across acquisition, activation, retention, expansion.',
    requiredInputs: ['product', 'ICP', 'motion (PLG/SLG)', 'current metrics'],
    optionalInputs: ['pricing', 'funnel data'],
    relevantSkills: ['saas.saas-go-to-market', 'plg.activation-metric-definition', 'saas.expansion-revenue'],
    outputStructure: ['north star', 'AARRR plan', 'experiments', 'measurement', 'roadmap'],
    approvalNotes: 'Spend/execution requires approval.',
  },
  {
    name: 'ecommerce_growth_plan',
    title: 'Create an e-commerce growth plan',
    description: 'Build an e-commerce growth plan (acquisition, AOV, retention, margin-aware).',
    requiredInputs: ['store/platform', 'products & margins', 'objectives'],
    optionalInputs: ['ROAS/MER targets', 'inventory constraints'],
    relevantSkills: ['ecommerce.conversion-rate-improvement', 'ecommerce.repeat-purchase', 'paid-social.catalogue-campaign-planning'],
    outputStructure: ['acquisition plan', 'AOV/retention plan', 'promotion calendar', 'measurement (ROAS/MER/CM)', 'safeguards'],
    approvalNotes: 'Spend/execution requires approval.',
  },
  {
    name: 'real_estate_lead_plan',
    title: 'Create a real-estate lead-generation plan',
    description: 'Plan compliant real-estate lead generation and nurture.',
    requiredInputs: ['property/development or service', 'location', 'buyer/seller focus'],
    optionalInputs: ['budget', 'CRM', 'compliance constraints'],
    relevantSkills: ['real-estate.lead-generation-campaign', 'real-estate.lead-qualification', 'real-estate.agent-follow-up-workflow'],
    outputStructure: ['segments', 'campaign plan', 'lead funnel', 'qualification', 'nurture', 'compliance', 'CPL dashboard'],
    approvalNotes: 'Spend/publishing requires approval; fair-advertising and accuracy safeguards apply.',
  },
  {
    name: 'retail_promotion_plan',
    title: 'Create a retail promotion plan',
    description: 'Plan a store/omnichannel retail promotion.',
    requiredInputs: ['store(s)/location', 'offer', 'objective', 'dates'],
    optionalInputs: ['inventory', 'margins', 'loyalty base'],
    relevantSkills: ['retail.local-promotion', 'retail.seasonal-retail-campaign', 'retail.loyalty-programme'],
    outputStructure: ['audiences', 'offer & rules', 'channels', 'inventory safeguards', 'measurement', 'post-promo analysis'],
    approvalNotes: 'Spend/publishing requires approval.',
  },
  {
    name: 'create_automation_workflow',
    title: 'Create a marketing automation workflow',
    description: 'Specify a marketing automation workflow with triggers and error handling.',
    requiredInputs: ['trigger', 'desired outcome', 'systems involved'],
    optionalInputs: ['data mapping', 'volume', 'platform (n8n/Make/Zapier)'],
    relevantSkills: ['automation.marketing-workflow-design', 'automation.error-handling-design'],
    outputStructure: ['trigger-action map', 'data flow', 'error handling', 'idempotency', 'observability', 'approvals'],
    approvalNotes: 'Actions with external side effects require approval.',
  },
  {
    name: 'review_compliance',
    title: 'Review marketing compliance',
    description: 'Screen a marketing activity for privacy, consent and policy risks.',
    requiredInputs: ['activity description', 'audience/region', 'channel'],
    optionalInputs: ['data sources', 'claims', 'consent basis'],
    relevantSkills: ['compliance.marketing-compliance-assessment', 'compliance.consent-assessment'],
    outputStructure: ['risk findings', 'required checks', 'items needing legal review', 'recommendation'],
    approvalNotes: 'Flags legal-review needs; not legal advice.',
  },
  {
    name: 'executive_marketing_summary',
    title: 'Create an executive marketing summary',
    description: 'Summarise marketing performance and priorities for executives.',
    requiredInputs: ['period', 'headline KPIs', 'business context'],
    optionalInputs: ['targets', 'initiatives', 'budget'],
    relevantSkills: ['reporting.executive-summary', 'reporting.board-ready-marketing-summary'],
    outputStructure: ['headline outcomes', 'what changed & why', 'risks', 'decisions needed', 'next quarter priorities'],
    approvalNotes: 'Read-only.',
  },
];
